### ISSUE TITLE
aliases for product and sum types

### ISSUE THREAD

**Issue by opsb** [expede/algae#29]
The following works but I'm required to fully qualify `Rabbitmq.Config.ExchangeType` when referring to that type from `Exchange`. 
```
defmodule Rabbitmq.Config do
  import Algae

  alias __MODULE__.ExchangeType # this doesn't work

  defmodule ExchangeType do
    defsum do
      defdata(Topic :: none())
      defdata(Direct :: none())
      defdata(Fanout :: none())
      defdata(Headers :: none())
    end
  end

  defdata Exchange do
    name :: String.t()
    type :: Rabbitmq.Config.ExchangeType.t()
  end
end
```
Is it possible to alias `ExchangeType` so that I can refer to it without it's namespace in `Exchange`?

**Comment by hariroshan** [comment]
I had this problem too. It only happens for defining types. Other than that, you can ExchangeType inside any methods in the module
